set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

" Config for MacVim

" UI
set number
set relativenumber
set cursorline

" Editing
set clipboard=unnamed
set expandtab
set mouse=a
set smartcase

" Indent
set shiftwidth=2
set shiftround
set smartindent
set tabstop=2

" Autoread
set autoread
au FocusGained,BufEnter * checktime

" Font
set guifont=MapleMonoNerdFontCompleteM-Regular:h15
set macligatures

" Theme
packadd! onedark.vim
colorscheme onedark

try
    set undodir=~/.vim_runtime/temp_dirs/undodir
    set undofile
catch
endtry
